### ISSUE TITLE
Setup script does not run unless you choose default options

### ISSUE THREAD

**Issue by lummoj** [compulab-yokneam/meta-bsp-imx8mm#1]
When I run:
MACHINE=ucm-imx8m-mini DISTRO=fsl-imx-xwayland  source sources/meta-bsp-imx8mm/tools/setup-imx8mm-env -b build-xwayland

And then reach the user config step, if you choose any non-default values such as 'no' for chrome the script produces an error and exits:

chrome configuration [ yes ] (Ctrl^C -- exit) : 3
cat: /tmp/userKT2: No such file or directory

It works fine if you say yes, this is on a vanilla Ubuntu 16.04.4 with the required Yocto packages installed.

**Comment by vraevsky** [comment]
Thanks for reporting on the issue.
Already fixed by:
https://github.com/compulab-yokneam/meta-bsp-imx8mm/commit/aef572bced44dca607ab0553691ff3c7f6eb5945
