### ISSUE TITLE
Firmware-imx-sdma-imx7d should be linux-firmware-imx-sdma-im7d

### ISSUE THREAD

**Issue by mwsoverdick** [compulab-yokneam/meta-bsp-imx8mm#11]
https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/735984dddac67c79285aba11093fcdd2058e515a/conf/layer.conf#L18

In Yocto 3.1.7 builds fail due to `firmware-imx-sdma-imx7d` in this recipe, instead of `linux-firmware-imx-sdma-im7d`

**Comment by vraevsky** [comment]
Thanks for reporting on the issue.
Fixed:
https://github.com/compulab-yokneam/meta-bsp-imx8mm/commit/724858d3fd92305bec6c468e0fb3c8591d7a16cf

**Comment by mwsoverdick** [comment]
Thank you!
