### ISSUE TITLE
Build failure: wireguard-module

### ISSUE THREAD

**Issue by akash-roboticist** [compulab-yokneam/meta-bsp-imx8mm#12]
Looking for some guidence if I am doing something wrong or this is an upstream issue.

Using the instructions in https://mediawiki.compulab.com/w/index.php?title=Building_IOT-GATE-iMX8_and_SBC-IOT-iMX8_Yocto_Linux_images, I am able to build the Yocto Zeus images for IOT-GATE-iMX8, but it fails if, I add `wireguard-tools`  `wireguard-module` to the `CORE_IMAGE_EXTRA_INSTALL` in `conf/local.conf`

Here's error - 
```
Summary: 1 task failed:
  /home/dev/sources/meta-openembedded/meta-networking/recipes-kernel/wireguard/wireguard-module_0.0.20190913.bb:do_compile
```

I guess it is likely, one of the sources for wireguard needs updating.

**Comment by vraevsky** [comment]
Fixed: https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8-dev/recipes-kernel/linux/wireguard/wireguard-module_0.0.20190913.bbappend

**Comment by vraevsky** [comment]
Fixed: https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8-dev/recipes-kernel/linux/wireguard-module_0.0.20190913.bbappend

**Comment by vraevsky** [comment]
Fixed: https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8-dev/recipes-kernel/wireguard/wireguard-module_0.0.20190913.bbappend
