### ISSUE TITLE
SDP support on IOT-GATE-iMX8 EVK

### ISSUE THREAD

**Issue by danie007** [compulab-yokneam/meta-bsp-imx8mm#13]
We're working on [IOT-GATE-iMX8 EVK](https://www.compulab.com/products/iot-gateways/iot-gate-imx8-industrial-arm-iot-gateway/#evalkit) and building the **Yocto Linux images** based on [this guide](https://mediawiki.compulab.com/w/index.php?title=Building_IOT-GATE-iMX8_and_SBC-IOT-iMX8_Yocto_Linux_images).

We want to enable **SDP** to work with **UUU Tool** but it seems like that the SDP support on SPL is scrapped out on the BSP.

We're getting the following error,

```shell
U-Boot SPL 2020.04-iot-gate-imx8-2.3-5.4.24-2.1.0+g4979a99482 (May 28 2021 - 06:32:44 +0000)
power_bd71837_init
DDRINFO(D): Nanya 2048G
DDRINFO: start DRAM init
DDRINFO:ddrphy calibration done
DDRINFO: ddrmix config done
DDRINFO(M): mr5-8 [ 0x5000010 ]
DDRINFO(E): mr5-8 [ 0x5000010 ]
Back to ROM, SDP
```

We've already [raised this on UUU tool repo](https://github.com/NXPmicro/mfgtools/issues/272).

### We would like to have a BSP with SDP support.

---

CC @tkmozhi

**Comment by vraevsky** [comment]
Please try this out: https://drive.google.com/drive/folders/168w7D4BhUxcV3ZAsNHjhCJfVWFBP9G5J?usp=sharing

**Comment by vraevsky** [comment]
SDP port is J4.

**Comment by vraevsky** [comment]
SDP: https://github.com/compulab-yokneam/meta-bsp-imx8mm/tree/iot-gate-imx8-dev

**Comment by danie007** [comment]
@vraevsky appreciate your quick support. ✌🏾 We've verified it on the `CompuLab IOT-GATE-IMX8 EVK` and it's working as expected. 👍🏾

Thanks for this [patch note](https://github.com/compulab-yokneam/meta-bsp-imx8mm/commit/a804dc61c80f6193a1a8a1f9914c89b31ff7f031#commitcomment-52128021) as well. **By any chance it'll result in a release**?

---

CC @tkmozhi

**Comment by vraevsky** [comment]
Good luck, thanks for your reply.
