### ISSUE TITLE
Update u-boot defconfig to include "CONFIG_SUPPORT_RAW_INITRD" for iot-gate-imx8

### ISSUE THREAD

**Issue by RuhanSA079** [compulab-yokneam/meta-bsp-imx8mm#15]
As per issue title, Ubuntu Core does not boot, due to current u-boot binary not supporting raw initrd images.
"CONFIG_SUPPORT_RAW_INITRD=y"

**Comment by RuhanSA079** [comment]
Pinging @vraevsky 
I already built a working u-boot image, for Ubuntu Core. (with CONFIG_SUPPORT_RAW_INITRD=y)

Board seems to be booting just fine.

**Comment by vraevsky** [comment]
Thanks,

we'll add the raw_initrd to the defconfig.
