### ISSUE TITLE
Can not reproduce kernel build for IOT-GATE-iMX8

### ISSUE THREAD

**Issue by xile273** [compulab-yokneam/meta-bsp-imx8mm#16]
We're working on a project using the IOT-GATE-iMX8. 
We need the IOT-GATE's CAN interface to support ISO-TP which is not integrated into Linux kernels older than 5.10. 
I'm not able to reproduce the kernel build provided on your website using the official documentation.

Would you able to give me instructions on how to produce the can-isotp kernel module that can be imported on the provided kernel?
Alternatively how can the boot partition (mmcblk2p1) be modified in order to boot a custom built kernel (which filesystem is it using)?

Here is the link to the can-isotp kernel module: https://github.com/hartkopp/can-isotp

Thanks in advance and kind regards,
Alexander Hölzl

**Comment by vraevsky** [comment]
Hi @xile273,

Please make use of this manual:
https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/iot-gate-imx8-dev/Documentation/linux_kernel_build.md

Let me know whether it works.

BR,
Val.

**Comment by xile273** [comment]
Yeah, I just got it to work. 
I was just confused on how to actually use the kernel that I build according to your manual. 
Maybe you could add a small explanation in your documentation?

Thank you for your help, and very quick response.

Kind regards
Alexander Hölzl
