### ISSUE TITLE
uboot 2021.04 hangs on IOT-GATE-IMX8

### ISSUE THREAD

**Issue by carmelomigliore** [compulab-yokneam/meta-bsp-imx8mm#17]
Hello, i did a yocto build with dunfell and meta-bsp-imx8mm at tag revision "iot-gate-imx8_r3.0". I flashed it on a iot-gate-imx8 devkit but the resulting u-boot (imx-boot) hangs during initialization. 
In order to let it work I had to revert the patch "0103-Revert-legacy-changes.patch" and then everything started correctly.
Is this expected? Am I missing something?
Thanks
Carmelo

**Comment by vraevsky** [comment]
Fixed in iot-gate-imx8_r3.1
