### ISSUE TITLE
Readme guide for rel3.2.1 and rel3.2  does not work, when run from the scratch

### ISSUE THREAD

**Issue by jyurdal** [compulab-yokneam/meta-bsp-imx8mm#22]
I have performed the steps to build the yocto project for rel3.2.1 but I get the error when running repo sync:
```
repo sync
remote: Enumerating objects: 1372, done.
remote: Counting objects: 100% (708/708), done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 1372 (delta 561), reused 640 (delta 506), pack-reused 664
Fetching: 25% (4/16) 0:07 | 2 jobs | 0:04 meta-bsp-imx8mm @ sources/meta-bsp-imx8mm
fatal: couldn't find remote ref refs/heads/iot-gate-imx8_r3.2.1
```
I have eddited the xml file with the revisions where I have replaced the tag with the corresponding hash and it works:
diff -Nur .repo/local_manifests/imx_5.15.32-2.0.0-compulab.xml /home/jyu/imx_5.15.32-2.0.0-compulab.xml 
--- .repo/local_manifests/imx_5.15.32-2.0.0-compulab.xml	2023-06-20 14:31:10.932643495 +0200
+++ /home/jyu/imx_5.15.32-2.0.0-compulab.xml	2023-06-20 14:20:01.154525878 +0200
@@ -5,7 +5,7 @@
 
```
   <project name="meta-compulab" remote="compulab" revision="6316d8ca737f7460ea24d83f3aeec9f8d00b6e8a" path="sources/meta-compulab"/>
   <project name="meta-compulab-bsp" remote="compulab" revision="7f5882eb9bd139e4dde204ffa6b0aa96577b36d0" path="sources/meta-compulab-bsp"/>
-  <project name="meta-bsp-imx8mm" remote="compulab" revision="iot-gate-imx8_r3.2.1" path="sources/meta-bsp-imx8mm" >
+  <project name="meta-bsp-imx8mm" remote="compulab" revision="6a9d624d4fdd1b7031d6e69cbb2eadef74f0cb3c" path="sources/meta-bsp-imx8mm" >
     <linkfile src="tools/compulab-setup-env" dest="compulab-setup-env" />
   </project>
```

I think initially tags are not available for the repo sync command if git repository was not checked out before.

**Comment by kkapranov** [comment]
Hi Joanna,

Thank you for pointing it out.
Please find the fix on the dedicated branch  https://github.com/compulab-yokneam/meta-bsp-imx8mm/tree/iot-gate-imx8-r3.2.1

**Comment by jyurdal** [comment]
Thanks

**Comment by tduf** [comment]
@kkapranov Could you please update the following wiki page which still points to the not working 3.2 tag: https://mediawiki.compulab.com/w/index.php?title=IOT-GATE-IMX8:_Yocto_Linux:_Building_Yocto_image

**Comment by kkapranov** [comment]
> @kkapranov Could you please update the following wiki page which still points to the not working 3.2 tag: https://mediawiki.compulab.com/w/index.php?title=IOT-GATE-IMX8:_Yocto_Linux:_Building_Yocto_image

Sorry for the delay.
Done
