### ISSUE TITLE
The eMMC module is installed in socket P14

### ISSUE THREAD

**Issue by jyurdal** [compulab-yokneam/meta-bsp-imx8mm#24]
I have eMMC module in socket P14 but it is not possible to see the eMMC device from the Yocto build. I do not have jumper E1 set. To  use extra module is it required to set the E1 jumper and boot from the extra module or can it be accessed when booting from internal eMMC?

**Comment by kkapranov** [comment]
Hi Joanna,

The jumper ALT_BOOT (marked E1) is intended mainly for unbricking purpose.
The additional eMMC is accessible on Linux as block device /dev/mmcblk1 off-the-shelf, if installed. Note, that the additional eMMC is not accessible on boot loader.

**Comment by jyurdal** [comment]
I have  a recovery image installed in P14 using IOTG-ACC-M2SD and I can boot from it if E1 jumper is there. I can not see it from LInux (Yocto build r.3.2.1):
```
root@iot-gate-imx8:~# ls /dev/mm*                                           
/dev/mmcblk2       /dev/mmcblk2boot1  /dev/mmcblk2p2
/dev/mmcblk2boot0  /dev/mmcblk2p1     /dev/mmcblk2rpmb

```
I shouldn't I be able to see it? I could not find much in the manual of how to use external eMMC.
Thanks for the support.

**Comment by kkapranov** [comment]
The extension board EB-M2SD (catalog name  IOTG-ACC-M2SD) is but uSD card reader; it is disabled in the DT in favor of  eMMC storage board EB-eMMC (see sec. 'Secondary Storage' of [1]).
The purpose of the board EB-M2SD in unbricking of the device, in case of the boot loader is inoperable; it works with the E1 jumper bridged. Of course, it may be enabled in the Linux via device-tree, providing that using of the EB-eMMC isn't designed.

[1] https://www.compulab.com/products/iot-gateways/iot-gate-imx8-industrial-arm-iot-gateway/#ordering

**Comment by jyurdal** [comment]
Thanks
