### ISSUE TITLE
bitbake error

### ISSUE THREAD

**Issue by metekhann** [compulab-yokneam/meta-bsp-imx8mm#26]
Hi, i get a error at bitbake step,
"ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed: git-lfs bison tree git-lfs".
could you help me,
thanks

**Comment by vraevsky** [comment]
The ERROR message contains the solution: please install them in order to proceed: git-lfs bison tree git-lfs".
Issue: sudo apt-get install git-lfs bison tree
