### ISSUE TITLE
Missing bt-start recipe.

### ISSUE THREAD

**Issue by marcinbis** [compulab-yokneam/meta-bsp-imx8mm#3]
I am working on rel_imx_5.4.24_2.1.0-dev branch.

```
$ time bitbake -k fsl-image-qt5-validation-imx
Parsing recipes: 100% |################################################################| Time: 0:00:22
Parsing of 3215 .bb files complete (0 cached, 3215 parsed). 4673 targets, 247 skipped, 2 masked, 0 err
ors.
ERROR: No recipes available for:
  /home/marcin/compulab/sources/meta-bsp-imx8mm/recipes-bsp/bt-start/bt-start_%.bbappend

Summary: There was 1 ERROR message shown, returning a non-zero exit code.
```

Build continues after disabling the bbappend file.

**Comment by vraevsky** [comment]
Please post the bblayers.conf

**Comment by Stimfarmer** [comment]
> I am working on rel_imx_5.4.24_2.1.0-dev branch.
> 
> ```
> $ time bitbake -k fsl-image-qt5-validation-imx
> Parsing recipes: 100% |################################################################| Time: 0:00:22
> Parsing of 3215 .bb files complete (0 cached, 3215 parsed). 4673 targets, 247 skipped, 2 masked, 0 err
> ors.
> ERROR: No recipes available for:
>   /home/marcin/compulab/sources/meta-bsp-imx8mm/recipes-bsp/bt-start/bt-start_%.bbappend
> 
> Summary: There was 1 ERROR message shown, returning a non-zero exit code.
> ```
> 
> Build continues after disabling the bbappend file.

Hi, bt-start recipe is available in layer https://github.com/compulab-yokneam/meta-compulab if I am not mistaken.

**Comment by vraevsky** [comment]
The latest layer conf has this bbpappend masked.
