### ISSUE TITLE
README.md is wrong on rel_imx_5.4.24_2.1.0-dev branch

### ISSUE THREAD

**Issue by ikozic** [compulab-yokneam/meta-bsp-imx8mm#4]
The readme.md suggests that both mcm-imx8m-mini and ucm-imx8m-mini dev kits are supported. However paragraph **1.2 Download CompuLab meta layer** suggests to clone meta-bsp-imx8mm on a tag rather than this branch:
/`git clone -b rel_imx_5.4.24_2.1.0-1.0 https://github.com/compulab-yokneam/meta-bsp-imx8mm.git sources/meta-bsp-imx8mm/`
Yocto build fails for ucm-imx8m-mini fails since tag **rel_imx_5.4.24_2.1.0-1.0** clearly does not support ucm-imx8m-mini as written in its README.md. Cloning with rel_imx_5.4.24_2.1.0-dev works.
Please fix.

**Comment by vraevsky** [comment]
https://github.com/compulab-yokneam/meta-bsp-imx8mm/blob/rel_imx_5.4.24_2.1.0-1.0/README.md claims that "Supported CompuLab machines: mcm-imx8-mini"
ucm-imx8m-mini 5.4.24_2.1 support is in development branch only.

**Comment by ikozic** [comment]
Indeed, but the readme in the development branch rel_imx_5.4.24_2.1.0-dev claims that both mcm- and ucm- kits are supported and then suggesting to clone Compulab's repo on rel_imx_5.4.24_2.1.0-1.0 tag, which clearly does not support ucm- kit. Following exact instructions results in failed build for ucm- module.

**Comment by vraevsky** [comment]
Thanks for reporting on the issue. Fixed:
https://github.com/compulab-yokneam/meta-bsp-imx8mm/commit/6f858387d1c0b8a11e2d39abaa39a4f011c96612

**Comment by ikozic** [comment]
Perfect, thanks!
