### ISSUE TITLE
cl-deploy from rel_imx_5.4.24_2.1.0-dev not updating Bootloader(s)

### ISSUE THREAD

**Issue by ikozic** [compulab-yokneam/meta-bsp-imx8mm#7]
Hi,
I've just successfully built and booted the new rel_2.1.0 from SD Card. However, cl-deploy script does not seem to update bootloaders, so I'm stuck with stock 2018.03 u-boot which seems to hang the new kernel.

Regarding the kernel hang, it sounds similar to one of the other issues here - the last line for me being:
`[    0.817148] mxs-dma 33000000.dma-controller: initialized`

The kernel and rootfs are properly updated (mmcblk2p1 and mmcblk2p2), but I noticed that you use JEDEC HW partitions on eMMC (boot0 and boot1 on mmcblk2) which are most likely containing u-boot and u-boot SPL in raw form without the FS. I've searched but I couldn't find a manual on how to manually flash this and with what exact artefact - could you please share a link or explanation on how to flash the bootloaders?
Thanks!

**Comment by vraevsky** [comment]
In order to update the board bootloader make us of the cl-uboot

**Comment by vraevsky** [comment]
Answered
